-- MySQL Script generated by MySQL Workbench
-- 12/04/18 11:22:56
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ProjetoUSJT
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ProjetoUSJT` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ProjetoUSJT` ;

-- -----------------------------------------------------
-- Table `ProjetoUSJT`.`LoginSistema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjetoUSJT`.`LoginSistema` (
  `idLoginSistema` INT NOT NULL AUTO_INCREMENT,
  `Login` VARCHAR(45) NULL,
  `Senha` VARCHAR(45) NULL,
  `Perfil` VARCHAR(45) NULL,
  PRIMARY KEY (`idLoginSistema`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjetoUSJT`.`ChefedoChefe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjetoUSJT`.`ChefedoChefe` (
  `idChefedoChefe` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  `LoginSistema_idLoginSistema` INT NOT NULL,
  PRIMARY KEY (`idChefedoChefe`),
  INDEX `fk_ChefedoChefe_LoginSistema1_idx` (`LoginSistema_idLoginSistema` ASC),
  CONSTRAINT `fk_ChefedoChefe_LoginSistema1`
    FOREIGN KEY (`LoginSistema_idLoginSistema`)
    REFERENCES `ProjetoUSJT`.`LoginSistema` (`idLoginSistema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjetoUSJT`.`ChefeImediato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjetoUSJT`.`ChefeImediato` (
  `idChefeImediato` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  `ChefedoChefe_idChefedoChefe` INT NOT NULL,
  `LoginSistema_idLoginSistema` INT NOT NULL,
  PRIMARY KEY (`idChefeImediato`),
  INDEX `fk_ChefeImediato_ChefedoChefe1_idx` (`ChefedoChefe_idChefedoChefe` ASC),
  INDEX `fk_ChefeImediato_LoginSistema1_idx` (`LoginSistema_idLoginSistema` ASC),
  CONSTRAINT `fk_ChefeImediato_ChefedoChefe1`
    FOREIGN KEY (`ChefedoChefe_idChefedoChefe`)
    REFERENCES `ProjetoUSJT`.`ChefedoChefe` (`idChefedoChefe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ChefeImediato_LoginSistema1`
    FOREIGN KEY (`LoginSistema_idLoginSistema`)
    REFERENCES `ProjetoUSJT`.`LoginSistema` (`idLoginSistema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjetoUSJT`.`Empregados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjetoUSJT`.`Empregados` (
  `idEmpregados` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  `Cpf` VARCHAR(45) NULL,
  `Rg` VARCHAR(45) NULL,
  `DataNascimento` DATE NULL,
  `Cargo` VARCHAR(45) NULL,
  `LoginSistema_idLoginSistema` INT NOT NULL,
  `ChefeImediato` INT NOT NULL,
  PRIMARY KEY (`idEmpregados`),
  INDEX `fk_Empregados_LoginSistema1_idx` (`LoginSistema_idLoginSistema` ASC),
  INDEX `fk_Empregados_ChefeImediato1_idx` (`ChefeImediato` ASC),
  CONSTRAINT `fk_Empregados_LoginSistema1`
    FOREIGN KEY (`LoginSistema_idLoginSistema`)
    REFERENCES `ProjetoUSJT`.`LoginSistema` (`idLoginSistema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Empregados_ChefeImediato1`
    FOREIGN KEY (`ChefeImediato`)
    REFERENCES `ProjetoUSJT`.`ChefeImediato` (`idChefeImediato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjetoUSJT`.`PrestacaoConta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjetoUSJT`.`PrestacaoConta` (
  `idSolictPrestacaoConta` INT NOT NULL AUTO_INCREMENT,
  `MesRef` VARCHAR(45) NULL,
  `CartaoC` VARCHAR(45) NULL,
  `Despesas` VARCHAR(45) NULL,
  `Descricao` VARCHAR(45) NULL,
  `Adiantamento` VARCHAR(45) NULL,
  `ValorPrest` VARCHAR(45) NULL,
  `Empregados_idEmpregados` INT NOT NULL,
  PRIMARY KEY (`idSolictPrestacaoConta`),
  INDEX `fk_PrestacaoConta_Empregados1_idx` (`Empregados_idEmpregados` ASC),
  CONSTRAINT `fk_PrestacaoConta_Empregados1`
    FOREIGN KEY (`Empregados_idEmpregados`)
    REFERENCES `ProjetoUSJT`.`Empregados` (`idEmpregados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjetoUSJT`.`Reembolso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjetoUSJT`.`Reembolso` (
  `idReembolso` INT NOT NULL AUTO_INCREMENT,
  `MesRef` VARCHAR(45) NULL,
  `ValorRembolso` VARCHAR(45) NULL,
  `Descricao` VARCHAR(45) NULL,
  `Empregados_idEmpregados` INT NOT NULL,
  PRIMARY KEY (`idReembolso`),
  INDEX `fk_Reembolso_Empregados1_idx` (`Empregados_idEmpregados` ASC),
  CONSTRAINT `fk_Reembolso_Empregados1`
    FOREIGN KEY (`Empregados_idEmpregados`)
    REFERENCES `ProjetoUSJT`.`Empregados` (`idEmpregados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjetoUSJT`.`DepartamentoContasPagar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjetoUSJT`.`DepartamentoContasPagar` (
  `idDepartamentoContaPagar` INT NOT NULL AUTO_INCREMENT,
  `PrestacaoConta_idSolictPrestacaoConta` INT NULL,
  `Reembolso_idReembolso` INT NULL,
  PRIMARY KEY (`idDepartamentoContaPagar`),
  INDEX `fk_DepartamentoContasPagar_PrestacaoConta1_idx` (`PrestacaoConta_idSolictPrestacaoConta` ASC),
  INDEX `fk_DepartamentoContasPagar_Reembolso1_idx` (`Reembolso_idReembolso` ASC),
  CONSTRAINT `fk_DepartamentoContasPagar_PrestacaoConta1`
    FOREIGN KEY (`PrestacaoConta_idSolictPrestacaoConta`)
    REFERENCES `ProjetoUSJT`.`PrestacaoConta` (`idSolictPrestacaoConta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DepartamentoContasPagar_Reembolso1`
    FOREIGN KEY (`Reembolso_idReembolso`)
    REFERENCES `ProjetoUSJT`.`Reembolso` (`idReembolso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjetoUSJT`.`StatusPedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjetoUSJT`.`StatusPedido` (
  `idStatusPedido` INT NOT NULL AUTO_INCREMENT,
  `Resultado` VARCHAR(45) NULL,
  `Date` DATETIME NULL DEFAULT NOW(),
  `idEmpregado` INT NOT NULL,
  `ChefeImediato_idChefeImediato` INT NOT NULL,
  `DepartamentoContasPagar_idDepartamentoContaPagar` INT NOT NULL,
  PRIMARY KEY (`idStatusPedido`),
  INDEX `fk_StatusPedido_Empregados1_idx` (`idEmpregado` ASC),
  INDEX `fk_StatusPedido_ChefeImediato1_idx` (`ChefeImediato_idChefeImediato` ASC),
  INDEX `fk_StatusPedido_DepartamentoContasPagar1_idx` (`DepartamentoContasPagar_idDepartamentoContaPagar` ASC),
  CONSTRAINT `fk_StatusPedido_Empregados1`
    FOREIGN KEY (`idEmpregado`)
    REFERENCES `ProjetoUSJT`.`Empregados` (`idEmpregados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_StatusPedido_ChefeImediato1`
    FOREIGN KEY (`ChefeImediato_idChefeImediato`)
    REFERENCES `ProjetoUSJT`.`ChefeImediato` (`idChefeImediato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_StatusPedido_DepartamentoContasPagar1`
    FOREIGN KEY (`DepartamentoContasPagar_idDepartamentoContaPagar`)
    REFERENCES `ProjetoUSJT`.`DepartamentoContasPagar` (`idDepartamentoContaPagar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
