/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formsview;

import functions.Funcionalidades;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import models.ChefeImediato;
import models.ChefedoChefe;
import models.UserEmpregado;
import models.UserLogin;

/**
 *
 * @author Marcos
 */
public class ChefeMediato extends javax.swing.JDialog {

    /**
     * Creates new form Chefe
     */
    public ChefeMediato(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../imagens/ic_chefe.png")));
        setTitle("Novo Chefe");    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        panelTitle = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        txtNomeChefe = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        lblLogin = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        Senhatxt = new javax.swing.JPasswordField();
        logintxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(150, 228, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelTitle.setBackground(new java.awt.Color(0, 144, 255));

        javax.swing.GroupLayout panelTitleLayout = new javax.swing.GroupLayout(panelTitle);
        panelTitle.setLayout(panelTitleLayout);
        panelTitleLayout.setHorizontalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        panelTitleLayout.setVerticalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jPanel2.add(panelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 90));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 140, 10));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nome do Chefe Mediato");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 260, -1));

        txtNomeChefe.setBackground(new java.awt.Color(150, 228, 255));
        txtNomeChefe.setBorder(null);
        txtNomeChefe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeChefeKeyTyped(evt);
            }
        });
        jPanel2.add(txtNomeChefe, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 140, 30));

        btnCadastrar.setBackground(new java.awt.Color(0, 144, 255));
        btnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ic_chefe.png"))); // NOI18N
        btnCadastrar.setText("Registrar Chefe");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 160, 40));

        lblLogin.setText("Login:");
        jPanel2.add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, 20));

        lblSenha.setText("Senha:");
        jPanel2.add(lblSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, 20));
        jPanel2.add(Senhatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 90, -1));
        jPanel2.add(logintxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 70, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        if (txtNomeChefe.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Por favor, preenchar todas os campos corretamente", "Informação", JOptionPane.INFORMATION_MESSAGE);
        }else{
            try {
                Funcionalidades func = new Funcionalidades();
                ChefedoChefe chefe = new ChefedoChefe();
                chefe.setNome(this.txtNomeChefe.getText());
                UserLogin user = new UserLogin();
                user.setLogin(logintxt.getText());
                user.setSenha(Senhatxt.getText());
                user.setPerfil("Chefe Mediato");
                chefe.setLogin(func.cadastrarLogin(user));
                if (func.cadastrarChefedoChefe(chefe)) {
                    JOptionPane.showMessageDialog(this, "Novo Chefe Cadastrado", "Informação", JOptionPane.INFORMATION_MESSAGE);
                    this.setVisible(false);
                }
                else{
                    JOptionPane.showMessageDialog(this, "Ocorreu um Erro", "Informação", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (SQLException ex) {
                Logger.getLogger(ChefeMediato.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void txtNomeChefeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeChefeKeyTyped
         int numero = 20;
        if (txtNomeChefe.getText().length()>= numero) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNomeChefeKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChefeMediato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChefeMediato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChefeMediato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChefeMediato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ChefeMediato dialog = new ChefeMediato(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Senhatxt;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JTextField logintxt;
    private javax.swing.JPanel panelTitle;
    private javax.swing.JTextField txtNomeChefe;
    // End of variables declaration//GEN-END:variables
}
