/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formsview;

import functions.Funcionalidades;
import java.awt.Toolkit;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import models.DadosUser;
import models.Reembolso;
import models.StatusPedido;

/**
 *
 * @author Marcos
 */
public class FormularioReembolso extends javax.swing.JDialog {

    private String idLogin,idNome, idPerfil, idEmpregado;
    /**
     * Creates new form FormularioReembolso
     */
    public FormularioReembolso(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../imagens/ic_novo_empregado.png")));
        setTitle("Reembolso");
        this.idRembolso.setText(Funcionalidades.IDMaxRembolso());
        this.idRembolso.setVisible(false);
        this.idDP.setText(Funcionalidades.IDMaxDP());
        this.idDP.setVisible(false);
        this.id.setText(String.valueOf(Principal.idEmpregado));
        this.idChefe.setText(String.valueOf(Principal.idChefeEmpregado));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnEnviarPedido = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        idRembolso = new javax.swing.JLabel();
        idDP = new javax.swing.JLabel();
        id = new java.awt.Label();
        idChefe = new java.awt.Label();
        txtMesRef = new javax.swing.JComboBox<>();
        lblMesRef = new javax.swing.JLabel();
        jSeparatorReemb = new javax.swing.JSeparator();
        txtValorReembolso = new javax.swing.JTextField();
        lblReembolso = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();
        lblDescricao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(150, 228, 255));

        btnEnviarPedido.setBackground(new java.awt.Color(0, 144, 255));
        btnEnviarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ic_status.png"))); // NOI18N
        btnEnviarPedido.setText("Registrar Conta");
        btnEnviarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarPedidoActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 144, 255));

        idRembolso.setText("idRembolso");

        idDP.setText("idDP");

        id.setText("id");

        idChefe.setText("id");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 384, Short.MAX_VALUE)
                .addComponent(idRembolso))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(idChefe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(idDP)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(idChefe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(idRembolso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idDP)
                        .addGap(2, 2, 2)
                        .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 33, Short.MAX_VALUE))
        );

        txtMesRef.setBackground(new java.awt.Color(0, 153, 153));
        txtMesRef.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um mês:", "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        txtMesRef.setToolTipText("");
        txtMesRef.setBorder(null);
        txtMesRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMesRefActionPerformed(evt);
            }
        });

        lblMesRef.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblMesRef.setText("Mês Referencia");

        jSeparatorReemb.setBackground(new java.awt.Color(0, 0, 0));

        txtValorReembolso.setBackground(new java.awt.Color(150, 228, 255));
        txtValorReembolso.setBorder(null);
        txtValorReembolso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorReembolsoActionPerformed(evt);
            }
        });
        txtValorReembolso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorReembolsoKeyTyped(evt);
            }
        });

        lblReembolso.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblReembolso.setText("Valor Reembolso");

        txtDescricao.setColumns(20);
        txtDescricao.setRows(5);
        txtDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescricaoKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtDescricao);

        lblDescricao.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblDescricao.setText("Descrição");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMesRef)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMesRef, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparatorReemb, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblReembolso)
                                    .addComponent(txtValorReembolso, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(lblDescricao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(btnEnviarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(lblMesRef)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtMesRef, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(lblReembolso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValorReembolso, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparatorReemb, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDescricao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnEnviarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtValorReembolsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorReembolsoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorReembolsoActionPerformed

    private void txtMesRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMesRefActionPerformed

    }//GEN-LAST:event_txtMesRefActionPerformed

    private void btnEnviarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarPedidoActionPerformed
        int idEmpregado = Integer.parseInt(id.getText());
        int idChefes = Integer.parseInt(idChefe.getText());
        if (txtMesRef.getSelectedIndex()== 0 || txtValorReembolso.getText().equals("") || txtDescricao.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Por favor, preenchar todas os campos corretamente", "Informação", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
        Reembolso rb = new Reembolso();
        rb.setEmpregadoId(idEmpregado);
        rb.setMesRef(this.txtMesRef.getSelectedItem().toString());
        rb.setValorReembolso(this.txtValorReembolso.getText());
        rb.setDescricao(this.txtDescricao.getText());

        Funcionalidades func = new Funcionalidades();
        if (func.cadastrarReembolso(rb)) {
            JOptionPane.showMessageDialog(this, "Pedido de Reembolso Cadastrado", "Informação", JOptionPane.INFORMATION_MESSAGE);
            func.enviaDPR(Integer.parseInt(this.idRembolso.getText()));
            StatusPedido sp = new StatusPedido();
            sp.setResultado("Em Elaboração");
            sp.setEmpregados_idEmpregados(idEmpregado);
            sp.setChefeImediato_idChefeImediato(idChefes);
            sp.setDepartamentoContasPagar_idDepartamentoContaPagar(Integer.parseInt(idDP.getText()));
            func.enviarStatus(sp);
            this.setVisible(false);

        }
            else{
                JOptionPane.showMessageDialog(this, "Ocorreu um Erro", "Informação", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEnviarPedidoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
            this.setVisible(false);
    }//GEN-LAST:event_formWindowClosing

    private void txtValorReembolsoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorReembolsoKeyTyped
        int numero = 10;
        if (txtValorReembolso.getText().length()>= numero) {
            evt.consume();
        }
        String caracteres="0987654321";
        if(!caracteres.contains(evt.getKeyChar()+"")){
        evt.consume();
        JOptionPane.showMessageDialog(rootPane, "Apenas Números");        
        }
    }//GEN-LAST:event_txtValorReembolsoKeyTyped

    private void txtDescricaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescricaoKeyTyped
        int numero = 40;
        if (txtDescricao.getText().length()>= numero) {
            evt.consume();
        }
    }//GEN-LAST:event_txtDescricaoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioReembolso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioReembolso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioReembolso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioReembolso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormularioReembolso dialog = new FormularioReembolso(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviarPedido;
    private java.awt.Label id;
    private java.awt.Label idChefe;
    private javax.swing.JLabel idDP;
    private javax.swing.JLabel idRembolso;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparatorReemb;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblMesRef;
    private javax.swing.JLabel lblReembolso;
    private javax.swing.JTextArea txtDescricao;
    private javax.swing.JComboBox<String> txtMesRef;
    private javax.swing.JTextField txtValorReembolso;
    // End of variables declaration//GEN-END:variables

   

    void receberdados(DadosUser user) {
        idLogin = user.getId();
        idNome = user.getLogin();
        idPerfil = user.getPerfil(); 
        System.out.println(user.getIdUser());
    }

    void receberdados(String[] dados) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    
}
