/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formsview;

import conexao.Conexao;
import functions.Funcionalidades;
import java.awt.Toolkit;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import models.UserEmpregado;
import models.UserLogin;

/**
 *
 * @author Marcos
 */
public class FormularioEmpregado extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    public FormularioEmpregado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../imagens/ic_novo_empregado.png")));
        setTitle("Novo Empregado");
        CarregarChefe();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        panelTitle = new javax.swing.JPanel();
        lblNomeEmpregado = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jSeparatorName = new javax.swing.JSeparator();
        lblCpfEmpregado = new javax.swing.JLabel();
        jSeparatorCpf = new javax.swing.JSeparator();
        lbRgEmpregado = new javax.swing.JLabel();
        jSeparatorRg = new javax.swing.JSeparator();
        jSeparatorCargo = new javax.swing.JSeparator();
        txtCargo = new javax.swing.JTextField();
        lbCargoEmpregado = new javax.swing.JLabel();
        jSeparatorData = new javax.swing.JSeparator();
        btnEnviarPedido = new javax.swing.JButton();
        lbServico = new javax.swing.JLabel();
        txtCpf = new javax.swing.JFormattedTextField();
        txtRg = new javax.swing.JFormattedTextField();
        txtDataNasc = new javax.swing.JFormattedTextField();
        lblSenha = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        logintxt = new javax.swing.JTextField();
        Senhatxt = new javax.swing.JPasswordField();
        combchefe = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(null);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(150, 228, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelTitle.setBackground(new java.awt.Color(0, 144, 255));

        javax.swing.GroupLayout panelTitleLayout = new javax.swing.GroupLayout(panelTitle);
        panelTitle.setLayout(panelTitleLayout);
        panelTitleLayout.setHorizontalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        panelTitleLayout.setVerticalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        jPanel2.add(panelTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 830, 90));

        lblNomeEmpregado.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblNomeEmpregado.setText("Nome Empregado:");
        jPanel2.add(lblNomeEmpregado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        txtNome.setBackground(new java.awt.Color(150, 228, 255));
        txtNome.setBorder(null);
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeKeyTyped(evt);
            }
        });
        jPanel2.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 410, 20));

        jSeparatorName.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparatorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 410, -1));

        lblCpfEmpregado.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lblCpfEmpregado.setText("CPF Empregado:");
        jPanel2.add(lblCpfEmpregado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jSeparatorCpf.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparatorCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 242, 160, 10));

        lbRgEmpregado.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lbRgEmpregado.setText("RG Empregado:");
        jPanel2.add(lbRgEmpregado, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, -1, -1));

        jSeparatorRg.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparatorRg, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 160, 10));

        jSeparatorCargo.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparatorCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 160, 10));

        txtCargo.setBackground(new java.awt.Color(150, 228, 255));
        txtCargo.setBorder(null);
        txtCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCargoActionPerformed(evt);
            }
        });
        txtCargo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCargoKeyTyped(evt);
            }
        });
        jPanel2.add(txtCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 160, 20));

        lbCargoEmpregado.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lbCargoEmpregado.setText("Cargo Empregado:");
        jPanel2.add(lbCargoEmpregado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jSeparatorData.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparatorData, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 160, 10));

        btnEnviarPedido.setBackground(new java.awt.Color(0, 144, 255));
        btnEnviarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ic_status.png"))); // NOI18N
        btnEnviarPedido.setText("Registrar");
        btnEnviarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarPedidoActionPerformed(evt);
            }
        });
        jPanel2.add(btnEnviarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, 220, 70));

        lbServico.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        lbServico.setText("Data Nascimento:");
        jPanel2.add(lbServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, -1, -1));

        txtCpf.setBackground(new java.awt.Color(150, 228, 255));
        txtCpf.setBorder(null);
        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(txtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 160, 20));

        txtRg.setBackground(new java.awt.Color(150, 228, 255));
        txtRg.setBorder(null);
        try {
            txtRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(txtRg, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 160, 20));

        txtDataNasc.setBackground(new java.awt.Color(150, 228, 255));
        txtDataNasc.setBorder(null);
        try {
            txtDataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(txtDataNasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 160, 20));

        lblSenha.setText("Senha:");
        jPanel2.add(lblSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, -1, 20));

        lblLogin.setText("Login:");
        jPanel2.add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 30, 20));
        jPanel2.add(logintxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 70, -1));
        jPanel2.add(Senhatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 90, -1));

        jPanel2.add(combchefe, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, 110, 40));

        jLabel1.setText("Selecionar Chefe:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 829, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarPedidoActionPerformed
        if (txtNome.getText().equals("") || txtCpf.getText().equals("") || txtRg.getText().equals("") || txtCargo.getText().equals("") || txtDataNasc.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Por favor, preenchar todas os campos corretamente", "Informação", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                Funcionalidades func = new Funcionalidades();
                UserEmpregado empregado = new UserEmpregado();
                empregado.setNome(this.txtNome.getText());
                empregado.setCpf(this.txtCpf.getText());
                empregado.setRg(this.txtRg.getText());
                String dia = txtDataNasc.getText().substring(0, 2);
                String mes = txtDataNasc.getText().substring(3, 5);
                String ano = txtDataNasc.getText().substring(6);
                String dataMysql = ano + "-" + mes + "-" + dia;
                empregado.setDataNascimento(dataMysql);
                empregado.setCargo(this.txtCargo.getText());
                UserLogin login = new UserLogin();
                login.setLogin(logintxt.getText());
                login.setSenha(Senhatxt.getText());
                login.setPerfil("Empregado");
                empregado.setChefeImediato(enviarID());
                empregado.setLoginSistema(func.cadastrarLogin(login));
                if (func.cadastrarEmpregado(empregado)) {
                    JOptionPane.showMessageDialog(this, "Novo Empregado Cadastrado", "Informação", JOptionPane.INFORMATION_MESSAGE);
                    this.setVisible(false);

                } else {
                    JOptionPane.showMessageDialog(this, "Ocorreu um Erro", "Informação", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (SQLException ex) {
                Logger.getLogger(FormularioEmpregado.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_btnEnviarPedidoActionPerformed
    public String convertStringToDate(Date indate) {
        String dateString = null;
        SimpleDateFormat sdfr = new SimpleDateFormat("dd/MM/yyyy");
        /*you can also use DateFormat reference instead of SimpleDateFormat 
    * like this: DateFormat df = new SimpleDateFormat("dd/MMM/yyyy");
         */
        try {
            dateString = sdfr.format(indate);
        } catch (Exception ex) {
            System.out.println(ex);
        }
        return dateString;
    }
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.setVisible(false);
    }//GEN-LAST:event_formWindowClosed

    private void txtCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCargoActionPerformed

    private void txtCargoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCargoKeyTyped
        int numero = 20;
        if (txtCargo.getText().length()>= numero) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCargoKeyTyped

    private void txtNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyTyped
         int numero = 40;
        if (txtNome.getText().length()>= numero) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNomeKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioEmpregado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioEmpregado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioEmpregado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioEmpregado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormularioEmpregado dialog = new FormularioEmpregado(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Senhatxt;
    private javax.swing.JButton btnEnviarPedido;
    private javax.swing.JComboBox<String> combchefe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparatorCargo;
    private javax.swing.JSeparator jSeparatorCpf;
    private javax.swing.JSeparator jSeparatorData;
    private javax.swing.JSeparator jSeparatorName;
    private javax.swing.JSeparator jSeparatorRg;
    private javax.swing.JLabel lbCargoEmpregado;
    private javax.swing.JLabel lbRgEmpregado;
    private javax.swing.JLabel lbServico;
    private javax.swing.JLabel lblCpfEmpregado;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblNomeEmpregado;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JTextField logintxt;
    private javax.swing.JPanel panelTitle;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JFormattedTextField txtDataNasc;
    private javax.swing.JTextField txtNome;
    private javax.swing.JFormattedTextField txtRg;
    // End of variables declaration//GEN-END:variables

    private void CarregarChefe(){
      try {
            Conexao conexao;
            conexao = new Conexao();
            String sql = "SELECT * FROM chefeimediato";
            PreparedStatement pst = conexao.getConexao().prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                String chefes = rs.getString("Nome");
                combchefe.addItem(chefes);
            }
            
            
        }catch(SQLException e){
            
        }
    }
    public int enviarID(){
         try {
            Conexao conexao;
            conexao = new Conexao();
            int id = 0;
            String sql = "SELECT idChefeImediato from chefeimediato where Nome = ?";
            PreparedStatement pst = conexao.getConexao().prepareStatement(sql);
            pst.setString(1,combchefe.getSelectedItem().toString() );
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                id = rs.getInt("idChefeImediato");
                return id;
            }else{
                JOptionPane.showMessageDialog(null,"Não foi encontrado nenhum chefe");
            }
        }catch(SQLException e){
            
        }
        return 0;
    }
}
