/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formsview;

import conexao.Conexao;
import functions.Funcionalidades;
import java.awt.Color;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import models.DadosUser;
import models.PrestacaoConta;

/**
 *
 * @author Marcos
 */
public class Principal extends javax.swing.JFrame {

    private FormularioPrestacao form;
    public static int idEmpregado,idChefeEmpregado;
    public static String nomeLogin;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../imagens/ic_adm.png")));
        setTitle("Menu Principal");
        Funcionalidades func = new Funcionalidades();
        func.Listar();
        txtIDEmpregado.setVisible(false);
        idChefe.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        sideshow = new javax.swing.JPanel();
        panel_menu = new javax.swing.JPanel();
        lblIcon = new javax.swing.JLabel();
        lblTextMenu = new javax.swing.JLabel();
        btnNovoEmpregado = new javax.swing.JButton();
        btnNovoChefe = new javax.swing.JButton();
        btnRelatorio = new javax.swing.JButton();
        btnStatusPedido = new javax.swing.JButton();
        StatusChefeMediato = new javax.swing.JButton();
        btnNovoChefedoChefe = new javax.swing.JButton();
        btnNovoReembolso = new javax.swing.JButton();
        btnNovaPrestacao = new javax.swing.JButton();
        StatusChefedoChefe = new javax.swing.JButton();
        menu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtID = new javax.swing.JLabel();
        txtLogin = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPerfil = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIDEmpregado = new javax.swing.JLabel();
        idChefe = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 400));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        bg.setBackground(new java.awt.Color(118, 186, 255));
        bg.setOpaque(false);
        bg.setPreferredSize(new java.awt.Dimension(800, 495));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sideshow.setBackground(new java.awt.Color(0, 102, 204));

        panel_menu.setBackground(new java.awt.Color(5, 146, 255));
        panel_menu.setToolTipText("");
        panel_menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ic_home.png"))); // NOI18N
        panel_menu.add(lblIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 50, 50));

        lblTextMenu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTextMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextMenu.setText("Menu");
        panel_menu.add(lblTextMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 120, 50));

        btnNovoEmpregado.setBackground(new java.awt.Color(0, 102, 255));
        btnNovoEmpregado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ic_novo_empregado.png"))); // NOI18N
        btnNovoEmpregado.setText("Novo Empregado");
        btnNovoEmpregado.setBorder(null);
        btnNovoEmpregado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoEmpregadoActionPerformed(evt);
            }
        });

        btnNovoChefe.setBackground(new java.awt.Color(0, 102, 255));
        btnNovoChefe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ic_chefe.png"))); // NOI18N
        btnNovoChefe.setText("Novo Chefe");
        btnNovoChefe.setBorder(null);
        btnNovoChefe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoChefeActionPerformed(evt);
            }
        });

        btnRelatorio.setBackground(new java.awt.Color(0, 102, 255));
        btnRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ic_chart.png"))); // NOI18N
        btnRelatorio.setText("Relatório Mensal");
        btnRelatorio.setBorder(null);
        btnRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioActionPerformed(evt);
            }
        });

        btnStatusPedido.setBackground(new java.awt.Color(0, 102, 255));
        btnStatusPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ic_status.png"))); // NOI18N
        btnStatusPedido.setText("Status Pedidos");
        btnStatusPedido.setBorder(null);
        btnStatusPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStatusPedidoActionPerformed(evt);
            }
        });

        StatusChefeMediato.setBackground(new java.awt.Color(0, 102, 255));
        StatusChefeMediato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ic_adm.png"))); // NOI18N
        StatusChefeMediato.setText("Status Chefe Imediato");
        StatusChefeMediato.setBorder(null);
        StatusChefeMediato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusChefeMediatoActionPerformed(evt);
            }
        });

        btnNovoChefedoChefe.setBackground(new java.awt.Color(0, 102, 255));
        btnNovoChefedoChefe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ic_chefe.png"))); // NOI18N
        btnNovoChefedoChefe.setText("Novo Chefe Mediato");
        btnNovoChefedoChefe.setBorder(null);
        btnNovoChefedoChefe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoChefedoChefeActionPerformed(evt);
            }
        });

        btnNovoReembolso.setBackground(new java.awt.Color(0, 102, 255));
        btnNovoReembolso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ic_adm.png"))); // NOI18N
        btnNovoReembolso.setText("Novo Reembolso");
        btnNovoReembolso.setBorder(null);
        btnNovoReembolso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoReembolsoActionPerformed(evt);
            }
        });

        btnNovaPrestacao.setBackground(new java.awt.Color(0, 102, 255));
        btnNovaPrestacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ic_adm.png"))); // NOI18N
        btnNovaPrestacao.setText("Nova Prestação");
        btnNovaPrestacao.setBorder(null);
        btnNovaPrestacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaPrestacaoActionPerformed(evt);
            }
        });

        StatusChefedoChefe.setBackground(new java.awt.Color(0, 102, 255));
        StatusChefedoChefe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ic_adm.png"))); // NOI18N
        StatusChefedoChefe.setText("Status Chefe Mediato");
        StatusChefedoChefe.setBorder(null);
        StatusChefedoChefe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatusChefedoChefeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sideshowLayout = new javax.swing.GroupLayout(sideshow);
        sideshow.setLayout(sideshowLayout);
        sideshowLayout.setHorizontalGroup(
            sideshowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_menu, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
            .addGroup(sideshowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sideshowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNovoEmpregado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNovoChefe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRelatorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnStatusPedido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(StatusChefeMediato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNovoChefedoChefe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNovoReembolso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNovaPrestacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(StatusChefedoChefe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        sideshowLayout.setVerticalGroup(
            sideshowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideshowLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(panel_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(btnNovoEmpregado, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNovoChefe, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNovoChefedoChefe, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(btnRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnStatusPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StatusChefeMediato, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StatusChefedoChefe, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNovaPrestacao, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNovoReembolso, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        bg.add(sideshow, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 700));

        menu.setBackground(new java.awt.Color(0, 144, 222));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sistema de Gerenciamento Departamento de Contas");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("ID:");

        txtID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtID.setText("ID:");

        txtLogin.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtLogin.setText("Nome");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Perfi:");

        txtPerfil.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtPerfil.setText("ID:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Olá,");

        txtIDEmpregado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtIDEmpregado.setText("ID:");

        idChefe.setText("ID CHEFE");

        jButton1.setBackground(new java.awt.Color(35, 139, 204));
        jButton1.setText("Logoff");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPerfil)
                        .addGap(392, 392, 392)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, menuLayout.createSequentialGroup()
                        .addComponent(idChefe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, menuLayout.createSequentialGroup()
                        .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtIDEmpregado, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, menuLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtID)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtPerfil)))
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLogin)
                            .addComponent(jLabel6))))
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(txtIDEmpregado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idChefe)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bg.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 1, 600, 180));

        jTableEmrpegados.setBackground(new java.awt.Color(102, 255, 255));
        jTableEmrpegados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "CPF", "RG", "Data Nascimento", "Cargo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableEmrpegados);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 590, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        bg.getAccessibleContext().setAccessibleParent(bg);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoEmpregadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoEmpregadoActionPerformed
        FormularioEmpregado fe = new FormularioEmpregado(this, true);
        fe.setVisible(true);
    }//GEN-LAST:event_btnNovoEmpregadoActionPerformed

    private void btnNovoChefeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoChefeActionPerformed
        Chefe dialog = new Chefe(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
        
    }//GEN-LAST:event_btnNovoChefeActionPerformed
   
    private void btnRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioActionPerformed
        FormularioRelatorio fr = new FormularioRelatorio();
        fr.setVisible(true);
    }//GEN-LAST:event_btnRelatorioActionPerformed

    private void btnStatusPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatusPedidoActionPerformed
        StatusPedidos sp = new StatusPedidos();
        sp.setVisible(true);
    }//GEN-LAST:event_btnStatusPedidoActionPerformed
    public static String VerificarChefe(){
        String sql = "SELECT MAX(idChefeImediato) AS id FROM chefeimediato";

        Conexao conexao = null;
        int id = 0;
            try {
                conexao = new Conexao();
            }catch(SQLException e){
                e.printStackTrace();
            }
        try{
            Statement st = conexao.getConexao().createStatement();
            ResultSet rs = st.executeQuery(sql);

            if(rs.next()){
                id = rs.getInt("id");
            }
            if (id == 0) {
                Object[] options = { "Sim", "Não" };
		int i = JOptionPane.showOptionDialog(null,
				"Seja Bem-Vindo ao Sistema \n"
                                        + "Não foi Encontrado Chefe Cadastrado deseja Cadastrar ?", "Chefe",
				JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null,
				options, options[0]);
		if (i == JOptionPane.YES_OPTION) {
                       Chefe dialog = new Chefe(new javax.swing.JFrame(), true);
                       dialog.setVisible(true);
		}
                else if(i == JOptionPane.NO_OPTION){
                    System.exit(0);
                }
            }
            return String.valueOf(id);
            }
            catch(SQLException e){
                return null;
        }
    }

    private void StatusChefeMediatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusChefeMediatoActionPerformed
            new StatusPedidosChef().setVisible(true);
    }//GEN-LAST:event_StatusChefeMediatoActionPerformed
    public void Dados (String dados[]){
        for (int i = 0; i < dados.length; i++) {
               this.txtID.setText(dados[0]);
               this.txtLogin.setText(dados[1]);
               this.txtPerfil.setText(dados[3]);
               if (txtPerfil.getText().equals("Empregado")) {
                this.idChefe.setText(dados[5]);
                }else if(txtPerfil.getText().equals("Chefe Imediato")){
                    
                }

        }
        if (txtPerfil.getText().equals("Admin")) {
            btnNovaPrestacao.setVisible(false);
            btnNovoReembolso.setVisible(false);
            StatusChefeMediato.setVisible(false);
            StatusChefedoChefe.setVisible(false);
            btnStatusPedido.setVisible(false);
        }
        else if(txtPerfil.getText().equals("Empregado")){
            btnNovoEmpregado.setVisible(false);
            btnNovoChefe.setVisible(false);
            btnNovoChefedoChefe.setVisible(false);
            btnRelatorio.setVisible(false);
            StatusChefeMediato.setVisible(false);
            StatusChefedoChefe.setVisible(false);
            this.txtIDEmpregado.setText(dados[4]);
        }
        else if(txtPerfil.getText().equals("Chefe Imediato")){
            btnNovoEmpregado.setVisible(false);
            btnNovoChefe.setVisible(false);
            btnNovoChefedoChefe.setVisible(false);
            btnRelatorio.setVisible(false);
            btnNovaPrestacao.setVisible(false);
            btnNovoReembolso.setVisible(false);
            btnStatusPedido.setVisible(false);
            StatusChefedoChefe.setVisible(false);
            this.txtIDEmpregado.setText(dados[4]);
        }
        else if((txtPerfil.getText().equals("Chefe Mediato"))){
            btnNovoEmpregado.setVisible(false);
            btnNovoChefe.setVisible(false);
            btnNovoChefedoChefe.setVisible(false);
            btnRelatorio.setVisible(false);
            StatusChefeMediato.setVisible(false);
            btnNovaPrestacao.setVisible(false);
            btnNovoReembolso.setVisible(false);
            btnStatusPedido.setVisible(false);
        }
        
         DadosUser user = new DadosUser();
         user.setId(this.txtID.getText());
         user.setLogin(this.txtLogin.getText());
         user.setPerfil(this.txtPerfil.getText());
         user.setIdUser(this.txtIDEmpregado.getText());
         try{
         idEmpregado = Integer.parseInt(this.txtIDEmpregado.getText());
         }catch(NumberFormatException e){
             System.out.println("Sem ID");
         }
         nomeLogin = this.txtLogin.getText();
         if (txtPerfil.getText().equals("Empregado")) {
            idChefeEmpregado = Integer.parseInt(this.idChefe.getText());    
        }
    } 
    private void btnNovoChefedoChefeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoChefedoChefeActionPerformed
        ChefeMediato fr = new ChefeMediato(new javax.swing.JFrame(), true);
        fr.setVisible(true);
    }//GEN-LAST:event_btnNovoChefedoChefeActionPerformed

    private void btnNovoReembolsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoReembolsoActionPerformed
        FormularioReembolso fr = new FormularioReembolso(new javax.swing.JFrame(), true);
        fr.setVisible(true);
    }//GEN-LAST:event_btnNovoReembolsoActionPerformed

    private void btnNovaPrestacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaPrestacaoActionPerformed
        FormularioPrestacao fr = new FormularioPrestacao(new javax.swing.JFrame(), true);
        fr.setVisible(true);
    }//GEN-LAST:event_btnNovaPrestacaoActionPerformed

    private void StatusChefedoChefeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatusChefedoChefeActionPerformed
        StatusPedidosChefeChefe chefe = new StatusPedidosChefeChefe();
        chefe.setVisible(true);
    }//GEN-LAST:event_StatusChefedoChefeActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
    }//GEN-LAST:event_formWindowClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        LoginSistema login = new LoginSistema();
        login.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
                VerificarChefe();

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton StatusChefeMediato;
    private javax.swing.JButton StatusChefedoChefe;
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnNovaPrestacao;
    private javax.swing.JButton btnNovoChefe;
    private javax.swing.JButton btnNovoChefedoChefe;
    private javax.swing.JButton btnNovoEmpregado;
    private javax.swing.JButton btnNovoReembolso;
    private javax.swing.JButton btnRelatorio;
    private javax.swing.JButton btnStatusPedido;
    private javax.swing.JLabel idChefe;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    public static final javax.swing.JTable jTableEmrpegados = new javax.swing.JTable();
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblTextMenu;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel panel_menu;
    private javax.swing.JPanel sideshow;
    private javax.swing.JLabel txtID;
    private javax.swing.JLabel txtIDEmpregado;
    private javax.swing.JLabel txtLogin;
    private javax.swing.JLabel txtPerfil;
    // End of variables declaration//GEN-END:variables
}
