/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formsview;

import conexao.Conexao;
import functions.Funcionalidades;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import models.StatusPedido;
import queriesaux.QuerysAux;

/**
 *
 * @author MGotado
 */
public class StatusPedidosChefeChefe extends javax.swing.JFrame {

    /**
     * Creates new form StatusPedidosChefeChefe
     */
    public StatusPedidosChefeChefe() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../imagens/ic_chefedochefe.png")));
        setTitle("Chefe do Chefe");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        nomeChefe1 = new javax.swing.JLabel();
        buscar = new javax.swing.JButton();
        comStatusChefe = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnReprovar = new javax.swing.JButton();
        btnAprovar = new javax.swing.JButton();
        txtIds = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        idComb = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(150, 228, 255));

        jPanel4.setBackground(new java.awt.Color(0, 144, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Pedido Acima de 2.500,00 do Chefe: ");

        nomeChefe1.setText("NomeChefe");

        buscar.setText("Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        comStatusChefe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Em Elaboração", "Aprovado", "Reprovado" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(comStatusChefe, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(179, 179, 179)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeChefe1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(11, 11, 11))
                    .addComponent(comStatusChefe, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomeChefe1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jLabel1.setText("ID:");

        btnReprovar.setText("Reprovar");
        btnReprovar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReprovarMouseClicked(evt);
            }
        });

        btnAprovar.setText("Aprovar");
        btnAprovar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAprovarMouseClicked(evt);
            }
        });
        btnAprovar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAprovarActionPerformed(evt);
            }
        });

        txtIds.setBackground(new java.awt.Color(0, 153, 255));
        txtIds.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtIds.setForeground(new java.awt.Color(0, 153, 204));
        txtIds.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtIds.setText("Selecione o ID Status que deseja Aprovar");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Prestação de Conta:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Reembolso:");

        TablePrestacaoChefedoChef.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Status", "Nome	", "RG	", "CPF	", "Cargo	", "Resultado	", "Mês	", "Despesas	", "Valor Prestação	"
            }
        ));
        jScrollPane3.setViewportView(TablePrestacaoChefedoChef);

        TableReembolsosChefe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Status", "Nome", "RG	", "CPF	", "Cargo	", "Resultado	", "Mês	", "Descrição	", "Valor Reembolso"
            }
        ));
        jScrollPane4.setViewportView(TableReembolsosChefe);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIds, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(idComb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(btnAprovar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReprovar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtIds, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAprovar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(idComb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnReprovar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public String IdsComboxReembs(String result){
        String sqlSelect = QuerysAux.combBoxReembChefdoChefe;
        //Chamo Conexao
         Conexao conexao;
         
         //Tratar se houve algum erro de Conexao
        try {
            conexao = new Conexao();
        }catch(SQLException e){
            return null;
            //Caso tenha retorna null
        }
        try 
            //Prepando Query (PreparedStatement)
            (PreparedStatement ps = 
                    //Incluindo Query
                conexao.getConexao().prepareStatement(sqlSelect);)
        {
            //Setando na Query Where passando o Codigo digitado
            ps.setString(1, result);

            ResultSet rs;
            try{
                rs = ps.executeQuery();
                
            while(rs.next()){
                idComb.addItem(rs.getString("idEmpregados"));
                }
                
            }catch(SQLException ex){
                ex.printStackTrace();
            }
            ps.executeQuery();
            
        } catch(SQLException e){
            try{
            conexao.getConexao().rollback();
            }catch(SQLException ex){
                ex.printStackTrace();
            }
        }
        return null;
    }
    public String IdsComboxPrests(String result){
        String sqlSelect = QuerysAux.combBoxPrestChefdoChefe;
        //Chamo Conexao
         Conexao conexao;
         
         //Tratar se houve algum erro de Conexao
        try {
            conexao = new Conexao();
        }catch(SQLException e){
            return null;
            //Caso tenha retorna null
        }
        try 
            //Prepando Query (PreparedStatement)
            (PreparedStatement ps = 
                    //Incluindo Query
                conexao.getConexao().prepareStatement(sqlSelect);)
        {
            //Setando na Query Where passando o Codigo digitado
            ps.setString(1, result);
            
            ResultSet rs;
            try{
                rs = ps.executeQuery();
                
            while(rs.next()){
                idComb.addItem(rs.getString("idEmpregados"));
                }
                
            }catch(SQLException ex){
                ex.printStackTrace();
            }
            ps.executeQuery();
            
        } catch(SQLException e){
            try{
            conexao.getConexao().rollback();
            }catch(SQLException ex){
                ex.printStackTrace();
            }
        }
        return null;
    }
    private void btnReprovarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReprovarMouseClicked
        Funcionalidades func = new Funcionalidades();
        if (func.ReprovarPedido(Integer.parseInt(idComb.getSelectedItem().toString()))) {
            JOptionPane.showMessageDialog(this, "Pedido Reprovado", "Informação", JOptionPane.INFORMATION_MESSAGE);
            StatusPedido sp = new StatusPedido();
            sp.setResultado(this.comStatusChefe.getSelectedItem().toString());
            func.ConsultaGeralPrestChefs(sp.getResultado());
            func.ConsultaGeralReembolsoChefs(sp.getResultado());
            idComb.removeAllItems();
            IdsComboxPrests(sp.getResultado());
            IdsComboxReembs(sp.getResultado());
        } else {
            JOptionPane.showMessageDialog(this, "ID Incorreto", "Informação", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnReprovarMouseClicked

    private void btnAprovarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAprovarMouseClicked
        Funcionalidades func = new Funcionalidades();
        if (func.AprovarPedido(Integer.parseInt(idComb.getSelectedItem().toString()))) {
            JOptionPane.showMessageDialog(this, "Pedido Aprovado", "Informação", JOptionPane.INFORMATION_MESSAGE);
            StatusPedido sp = new StatusPedido();
            sp.setResultado(this.comStatusChefe.getSelectedItem().toString());
            func.ConsultaGeralPrestChefs(sp.getResultado());
            func.ConsultaGeralReembolsoChefs(sp.getResultado());
            idComb.removeAllItems();
              IdsComboxPrests(sp.getResultado());
            IdsComboxReembs(sp.getResultado());

        } else {
            JOptionPane.showMessageDialog(this, "ID Incorreto", "Informação", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnAprovarMouseClicked

    private void btnAprovarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAprovarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAprovarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        StatusPedido sp = new StatusPedido();
        sp.setResultado(comStatusChefe.getSelectedItem().toString());
        Funcionalidades func = new Funcionalidades();
        func.ConsultaGeralPrestChefs(sp.getResultado() );
        func.ConsultaGeralReembolsoChefs(sp.getResultado());
        idComb.removeAllItems();
        func.ConsultaGeralPrestChefs(sp.getResultado());
        func.ConsultaGeralReembolsoChefs(sp.getResultado());
        IdsComboxReembs(sp.getResultado());
        IdsComboxPrests(sp.getResultado());
        if (comStatusChefe.getSelectedIndex() == 1) {
            btnAprovar.setVisible(false);
        }
        else{
            btnAprovar.setVisible(true);
        }
        if(comStatusChefe.getSelectedIndex() == 2){
            btnReprovar.setVisible(false);
        }
        else{
            btnReprovar.setVisible(true);
        }
    }//GEN-LAST:event_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StatusPedidosChefeChefe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StatusPedidosChefeChefe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StatusPedidosChefeChefe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StatusPedidosChefeChefe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StatusPedidosChefeChefe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static final javax.swing.JTable TablePrestacaoChefedoChef = new javax.swing.JTable();
    public static final javax.swing.JTable TableReembolsosChefe = new javax.swing.JTable();
    private javax.swing.JButton btnAprovar;
    private javax.swing.JButton btnConsulta;
    private javax.swing.JButton btnReprovar;
    private javax.swing.JButton buscar;
    private javax.swing.JComboBox<String> comStatusChefe;
    private javax.swing.JComboBox<String> combStatus;
    private javax.swing.JLabel id;
    private javax.swing.JComboBox<String> idComb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel nomeChefe;
    private javax.swing.JLabel nomeChefe1;
    private javax.swing.JLabel txtIds;
    // End of variables declaration//GEN-END:variables
}
