/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formsview;

import conexao.Conexao;
import functions.Funcionalidades;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import models.StatusPedido;
import queriesaux.QuerysAux;

/**
 *
 * @author MGotado
 */
public class StatusPedidosChef extends javax.swing.JFrame {

    /**
     * Creates new form StatusPedidosChef
     */
    public StatusPedidosChef() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../imagens/ic_chart.png")));
        setTitle("Status Pedido Chefe Mediato");
        this.id.setText(String.valueOf(Principal.idEmpregado));
        this.nomeChefe.setText(String.valueOf(Principal.nomeLogin));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        combStatus = new javax.swing.JComboBox<>();
        btnConsulta = new javax.swing.JButton();
        id = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomeChefe = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        btnReprovar = new javax.swing.JButton();
        btnAprovar = new javax.swing.JButton();
        combID = new javax.swing.JComboBox<>();
        txtIds = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(150, 228, 255));

        jPanel2.setBackground(new java.awt.Color(0, 144, 255));

        combStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Em Elaboração", "Aprovado", "Reprovado" }));

        btnConsulta.setText("Buscar");
        btnConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaActionPerformed(evt);
            }
        });

        id.setText("id");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Pedido de até 2.500,00 do Chefe: ");

        nomeChefe.setText("NomeChefe");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(combStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(176, 176, 176)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeChefe, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(id)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(id)
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeChefe, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        TableChefReemb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Status", "Nome", "RG", "CPF", "Cargo", "Resultado", "Mês", "Descrição", "Valor Reembolso"
            }
        ));
        jScrollPane1.setViewportView(TableChefReemb);

        TableChefPrest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Status", "Nome", "RG", "CPF", "Cargo", "Resultado", "Mês", "Despesas", "Valor Prestação"
            }
        ));
        jScrollPane2.setViewportView(TableChefPrest);

        jLabel1.setText("ID:");

        btnReprovar.setText("Reprovar");
        btnReprovar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReprovarMouseClicked(evt);
            }
        });

        btnAprovar.setText("Aprovar");
        btnAprovar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAprovarMouseClicked(evt);
            }
        });
        btnAprovar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAprovarActionPerformed(evt);
            }
        });

        txtIds.setBackground(new java.awt.Color(0, 153, 255));
        txtIds.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtIds.setForeground(new java.awt.Color(0, 153, 204));
        txtIds.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtIds.setText("Selecione o ID Status que deseja Aprovar");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Prestação de Conta:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Reembolso:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIds, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(10, 10, 10)
                                .addComponent(combID, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAprovar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnReprovar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(638, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 948, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIds, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAprovar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReprovar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combID, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(23, 23, 23))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(131, 131, 131)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(317, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public String IdsComboxReemb(String result, int idChefe){
        String sqlSelect = QuerysAux.combBoxReembChef;
        //Chamo Conexao
         Conexao conexao;
         
         //Tratar se houve algum erro de Conexao
        try {
            conexao = new Conexao();
        }catch(SQLException e){
            return null;
            //Caso tenha retorna null
        }
        try 
            //Prepando Query (PreparedStatement)
            (PreparedStatement ps = 
                    //Incluindo Query
                conexao.getConexao().prepareStatement(sqlSelect);)
        {
            //Setando na Query Where passando o Codigo digitado
            ps.setString(1, result);
            ps.setInt(2, idChefe);

            ResultSet rs;
            try{
                rs = ps.executeQuery();
                
            while(rs.next()){
                combID.addItem(rs.getString("idEmpregados"));
                }
                
            }catch(SQLException ex){
                ex.printStackTrace();
            }
            ps.executeQuery();
            
        } catch(SQLException e){
            try{
            conexao.getConexao().rollback();
            }catch(SQLException ex){
                ex.printStackTrace();
            }
        }
        return null;
    }
    public String IdsComboxPrest(String result, int idChefe){
        String sqlSelect = QuerysAux.combBoxPrestChef;
        //Chamo Conexao
         Conexao conexao;
         
         //Tratar se houve algum erro de Conexao
        try {
            conexao = new Conexao();
        }catch(SQLException e){
            return null;
            //Caso tenha retorna null
        }
        try 
            //Prepando Query (PreparedStatement)
            (PreparedStatement ps = 
                    //Incluindo Query
                conexao.getConexao().prepareStatement(sqlSelect);)
        {
            //Setando na Query Where passando o Codigo digitado
            ps.setString(1, result);
            ps.setInt(2, idChefe);
            
            ResultSet rs;
            try{
                rs = ps.executeQuery();
                
            while(rs.next()){
                combID.addItem(rs.getString("idEmpregados"));
                }
                
            }catch(SQLException ex){
                ex.printStackTrace();
            }
            ps.executeQuery();
            
        } catch(SQLException e){
            try{
            conexao.getConexao().rollback();
            }catch(SQLException ex){
                ex.printStackTrace();
            }
        }
        return null;
    }

    private void btnAprovarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAprovarMouseClicked
        Funcionalidades func = new Funcionalidades();
        int idChefe = Integer.parseInt(id.getText());
        if (func.AprovarPedido(Integer.parseInt(combID.getSelectedItem().toString()))) {
            JOptionPane.showMessageDialog(this, "Pedido Aprovado", "Informação", JOptionPane.INFORMATION_MESSAGE);
            StatusPedido sp = new StatusPedido();
            sp.setResultado(this.combStatus.getSelectedItem().toString());
            func.ConsultaGeralPrestChef(sp.getResultado(), idChefe);
            func.ConsultaGeralReembolsoChef(sp.getResultado(),idChefe);
            combID.removeAllItems();
            IdsComboxReemb(sp.getResultado(),idChefe);
            IdsComboxPrest(sp.getResultado(),idChefe);

        } else {
            JOptionPane.showMessageDialog(this, "ID Incorreto", "Informação", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnAprovarMouseClicked

    private void btnReprovarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReprovarMouseClicked
         Funcionalidades func = new Funcionalidades();
        int idChefe = Integer.parseInt(id.getText());
        if (func.ReprovarPedido(Integer.parseInt(combID.getSelectedItem().toString()))) {
            JOptionPane.showMessageDialog(this, "Pedido Reprovado", "Informação", JOptionPane.INFORMATION_MESSAGE);
            StatusPedido sp = new StatusPedido();
            sp.setResultado(this.combStatus.getSelectedItem().toString());
            func.ConsultaGeralPrestChef(sp.getResultado(),idChefe);
            func.ConsultaGeralReembolsoChef(sp.getResultado(),idChefe);
            combID.removeAllItems();
            IdsComboxReemb(sp.getResultado(),idChefe);
            IdsComboxPrest(sp.getResultado(),idChefe);
        } else {
            JOptionPane.showMessageDialog(this, "ID Incorreto", "Informação", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnReprovarMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
                this.setVisible(false);
    }//GEN-LAST:event_formWindowClosing

    private void btnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaActionPerformed
        StatusPedido sp = new StatusPedido();
        int idChefe = Integer.parseInt(id.getText());
        sp.setResultado(this.combStatus.getSelectedItem().toString());
        Funcionalidades func = new Funcionalidades();
        func.ConsultaGeralPrestChef(sp.getResultado(),idChefe );
        func.ConsultaGeralReembolsoChef(sp.getResultado(), idChefe);
        combID.removeAllItems();
        IdsComboxReemb(sp.getResultado(),idChefe);
        IdsComboxPrest(sp.getResultado(),idChefe);
        if (combStatus.getSelectedIndex() == 1) {
            btnAprovar.setVisible(false);
        }
        else{
            btnAprovar.setVisible(true);
        }
        if(combStatus.getSelectedIndex() == 2){
            btnReprovar.setVisible(false);
        }
        else{
            btnReprovar.setVisible(true);
        }  
    }//GEN-LAST:event_btnConsultaActionPerformed

    private void btnAprovarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAprovarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAprovarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StatusPedidosChef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StatusPedidosChef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StatusPedidosChef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StatusPedidosChef.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StatusPedidosChef().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static final javax.swing.JTable TableChefPrest = new javax.swing.JTable();
    public static final javax.swing.JTable TableChefReemb = new javax.swing.JTable();
    private javax.swing.JButton btnAprovar;
    private javax.swing.JButton btnConsulta;
    private javax.swing.JButton btnReprovar;
    private javax.swing.JComboBox<String> combID;
    private javax.swing.JComboBox<String> combStatus;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nomeChefe;
    private javax.swing.JLabel txtIds;
    // End of variables declaration//GEN-END:variables
}
